version: '3'
services:
#  reverseproxy:
#    image: reverseproxy
#    ports:
#      - 80:80
#      - 443:443
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:latest
    volumes:
      - /srv/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
    depends_on:
      - mqtt
    restart: unless-stopped
    ports: 
      - "8123:8123/tcp"
      - "51827:51827/tcp"
#      - "56700:56700/udp"
#      - "49339:49339/udp"
#      - "5353:5353/udp"
#      - "40133:40133/udp"
#    network_mode: host
  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:latest
    volumes:
      - /srv/homeassistant/mqtt/config:/mosquitto/config
      - /srv/homeassistant/mqtt/log:/mosquitto/log
      - /srv/homeassistant/mqtt/data:/mosquitto/data 
    ports:
      - "9001:9001"
      - "1883:1883"
    restart: unless-stopped 
