title: Unit 3121
resources:
  - url: /local/button-card/button-card.js
    type: module
views:
  - title: Main
    id: main
    cards:
      - &alerts
        type: entity-filter
        entities:
          - entity: sensor.balcony_door
            icon: mdi:door-open
          - entity: sensor.balcony_window
            icon: mdi:window-open
          - entity: sensor.front_door
            icon: mdi:door-open
          - entity: binary_sensor.home_away
            name: Nest Away
            icon: mdi:account-off
          - entity: input_boolean.away
          - entity: input_boolean.sleep
          - entity: input_boolean.vacation
        state_filter:
          - "open"
          - "on"
        show_empty: False
        card:
          type: glance
          show_state: false
      - type: "custom:button-card"
        entity: input_boolean.vacation
        show_state: true
      - type: picture-entity
        entity: camera.parking
        show_name: False
        show_state: False
      - type: horizontal-stack
        cards: 
         - type: sensor
           entity: sensor.hallway_thermostat_temperature
           title: Indoor Temp
           graph: line
           detail: 1
           hours_to_show: 24
         - type: sensor
           entity: sensor.wx_temperature
           title: Outdoor Temp
           graph: line
           detail: 1
           hours_to_show: 24
      - type: horizontal-stack
        cards: 
         - id: commute
           type: gauge
           entity: sensor.home_to_work
           title: Time to Work
           min: 10
           max: 60
           severity:
             green: 0
             yellow: 25
             red: 35
         - id: time-to-becca
           type: gauge
           entity: sensor.home_to_becca
           title: Time to Becca
           min: 20
           max: 70
           severity:
             green: 0
             yellow: 35
             red: 45
      - &thermostat
        type: thermostat
        entity: climate.hallway
      - id: all_lights
        type: entity-button
        entity: group.all_lights
        icon: mdi:home-modern
        name: Turn off all lights
        tap_action: toggle
      - id: hallway
        type: entity-button
        entity: light.hallway_overhead
        icon: mdi:lightbulb-outline
        name: All Hallway Lights
        tap_action: toggle
      - id: frondoor
        type: entity-button
        entity: light.hallway_front
        icon: mdi:lightbulb-outline
        name: Front Door Light
        tap_action: toggle
      - id: bedroom
        type: entity-button
        entity: light.bedroom_lamp
        icon: mdi:hotel
        tap_action: toggle
        name: Bedroom Lights
      - id: kitchen
        type: entity-button
        entity: light.kitchen_overhead
        icon: mdi:fridge
        tap_action: toggle
        name: Kitchen Overhead
  - title: Bedroom
    id: bedroom
    theme: dark-mode
    cards: 
      - *alerts
      - *thermostat
      - type: horizontal-stack
        cards:
        - type: light
          entity: light.bedroom_lamp
          icon: mdi:hotel
          tap_action: toggle
          name: Lamps
        - type: light
          entity: light.bedroom_overhead
          icon: mdi:ceiling-light
          tap_action: toggle
          name: Overhead
        - type: entity-button
          entity: input_boolean.sleep
          icon: mdi:hotel
          tap_action: toggle
          name: Sleep Mode
